/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#40484f",
        "outline": "#747686",
        "outline-variant": "#c3c5d7",
        "surface-container-highest": "#dfe2ec",
        "primary-container": "#2457d6",
        "on-secondary-fixed-variant": "#004495",
        "on-tertiary-fixed": "#151c23",
        "primary": "#003fb3",
        "tertiary-fixed": "#dce3ec",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#adc6ff",
        "surface": "#f9f9ff",
        "surface-container": "#ebeef8",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9f9ff",
        "secondary-container": "#2571e1",
        "inverse-on-surface": "#eef0fb",
        "primary-fixed": "#dce1ff",
        "surface-container-high": "#e5e8f2",
        "surface-variant": "#dfe2ec",
        "on-surface-variant": "#434654",
        "secondary": "#0058be",
        "surface-dim": "#d7dae4",
        "on-primary-container": "#d5dcff",
        "on-secondary-container": "#fefcff",
        "on-secondary": "#ffffff",
        "background": "#f9f9ff",
        "error-container": "#ffdad6",
        "tertiary": "#434a52",
        "inverse-primary": "#b5c4ff",
        "on-secondary-fixed": "#001a42",
        "primary-fixed-dim": "#b5c4ff",
        "surface-container-low": "#f1f3fd",
        "on-tertiary-container": "#d7dee7",
        "secondary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#c0c7d0",
        "on-tertiary": "#ffffff",
        "on-background": "#181c23",
        "on-error": "#ffffff",
        "surface-tint": "#1f54d3",
        "on-primary-fixed-variant": "#003cad",
        "tertiary-container": "#5b626a",
        "on-primary-fixed": "#00164d",
        "inverse-surface": "#2d3138",
        "on-surface": "#181c23"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
        mono: ["Inter", "monospace"],
        "technical-mono": ["Inter", "monospace"],
        "label-caps": ["Inter", "sans-serif"],
        "display-xl": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      }
    }
  },
  plugins: []
}
